src/Entity/Member.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MemberRepository")
 * @UniqueEntity("name",  message="Ce membre est déjà dans la guilde.")
 */
class Member
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $Kl;

    /**
     * @ORM\Column(type="integer")
     */
    private $bonus_malus;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\BoxMember", mappedBy="Member", orphanRemoval=true)
     */
    private $boxMembers;

    /**
     * @ORM\Column(type="boolean")
     */
    private $disabled;

    public function __construct()
    {
        $this->Box = new ArrayCollection();
        $this->boxMembers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getKl(): ?int
    {
        return $this->Kl;
    }

    public function setKl(int $Kl): self
    {
        $this->Kl = $Kl;

        return $this;
    }

    public function getBonusMalus(): ?int
    {
        return $this->bonus_malus;
    }

    public function setBonusMalus(int $bonus_malus): self
    {
        $this->bonus_malus = $bonus_malus;

        return $this;
    }

    /**
     * @return Collection|BoxMember[]
     */
    public function getBoxMembers(): Collection
    {
        return $this->boxMembers;
    }

    public function addBoxMember(BoxMember $boxMember): self
    {
        if (!$this->boxMembers->contains($boxMember)) {
            $this->boxMembers[] = $boxMember;
            $boxMember->setMember($this);
        }

        return $this;
    }

    public function removeBoxMember(BoxMember $boxMember): self
    {
        if ($this->boxMembers->contains($boxMember)) {
            $this->boxMembers->removeElement($boxMember);
            // set the owning side to null (unless already changed)
            if ($boxMember->getMember() === $this) {
                $boxMember->setMember(null);
            }
        }

        return $this;
    }

    public function getDisabled(): ?bool
    {
        return $this->disabled;
    }

    public function setDisabled(bool $disabled): self
    {
        $this->disabled = $disabled;

        return $this;
    }
}

src/Form/MemberType.php
<?php

namespace App\Form;

use App\Entity\Member;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class MemberType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('Kl')
            ->add('bonus_malus')
            ->add('disabled')
            ->add('button', SubmitType::class, ['label' => 'Valider'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Member::class,
        ]);
    }
}

src/Controller/MemberController.php
<?php
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Member;
use App\Form\MemberType;

class MemberController extends AbstractController
{

    /**
     *
     * @Route("/member", name="member_index")
     */
    public function index()
    {
        $memberRepository = $this->getDoctrine()->getRepository(Member::class);
        $members = $memberRepository->findAll();
        
        return $this->render('member/index.html.twig', [
            'members' => $members
        ]);
    }

    /**
     * Permet d'ajouter un nouveau membre
     * @Route("/member/add", name="member_add")
     * @param Request $request
     */
    public function addMember(Request $request)
    {
        $member = new Member();

        $form = $this->createForm(MemberType::class, $member);
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                $em = $this->getDoctrine()->getManager();
                
                $em->persist($member);
                $em->flush();
                
                $this->addFlash('success', 'le membre ' . $member->getName() . ' à correctement été ajouté');
                
                return $this->redirectToRoute('member_index');
            }
        }
        
        return $this->render('member/add.html.twig', [
            'form' => $form->createView()
        ]);
    }
    
    /**
     * Permet d'éditer un nouveau membre
     * @Route("/member/edit/{id}", name="member_edit")
     * @ParamConverter("member", options={"mapping": {"id": "id"}})
     * @param Request $request
     * @param Member $member
     */
    public function editMember(Request $request, Member $member)
    {
        $form = $this->createForm(MemberType::class, $member);
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                $em = $this->getDoctrine()->getManager();
                
                $em->persist($member);
                $em->flush();
                
                $this->addFlash('success', 'le membre ' . $member->getName() . ' à correctement été modifié');
                
                return $this->redirectToRoute('member_index');
            }
        }
        
        return $this->render('member/edit.html.twig', [
            'form' => $form->createView(),
            'member' => $member
        ]);
    }
    
    /**
     * Supprime un membre
     *
     * @Route("/member/delete/{id}", name="member_delete")
     * @ParamConverter("member", options={"mapping": {"id": "id"}})
     *
     * @param Member $member
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function deleteMember(Member $member)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($member);
        $entityManager->flush();
        
        $this->addFlash('success', 'le membre ' . $member->getName() . ' à correctement été supprimé');
        
        return $this->redirectToRoute('member_index');
    }
    
    /**
     * Active ou désactive un membre
     *
     * @Route("/member/disabled/{id}", name="member_disabled")
     * @ParamConverter("member", options={"mapping": {"id": "id"}})
     *
     * @param Member $member
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function disabledMember(Member $member)
    {
        $str = '';
        if($member->getDisabled() == 0)
        {
            $member->setDisabled(1);
            $str = 'bannis';
        }
        else
        {
            $member->setDisabled(0);
            $str = 'actif';
        }
        
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($member);
        $entityManager->flush();
        
        $this->addFlash('success', 'le membre ' . $member->getName() . ' est maintenant ' . $str);
        
        return $this->redirectToRoute('member_index');
    }
}

templates/member/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Création d'un nouveau membre{% endblock %}

{% block body %}
	<h1>Création d'un nouveau membre</h1>
	<div>
		<a href="{{path('member_index')}}"><span class="oi oi-arrow-thick-left"></span> Retour</a>
	</div>
	{{ form(form) }}
{% endblock %}

templates/member/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification de {{ member.name }}{% endblock %}

{% block body %}
	<h1>Modification de {{ member.name }}</h1>
	<div>
		<a href="{{path('member_index')}}"><span class="oi oi-arrow-thick-left"></span> Retour</a>
	</div>
	{{ form(form) }}
{% endblock %}

templates/member/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des membres de la guilde{% endblock %}

{% block body %}
	<h1>Gestion des membres de la guilde</h1>
	
	<a href="{{path('member_add')}}">Ajouter un membre</a>
	
		<table class="table table-striped">
  		<thead>
    		<tr>
      			<th scope="col">#</th>
      			<th scope="col">Name</th>
      			<th scope="col">KL</th>
      			<th scope="col">Bonus / Malus</th>
      			<th scope="col">Max level boss</th>
      			<th scope="col">Etat</th>
      			<th scope="col">Action</th>
    		</tr>
  		</thead>
  		<tbody>
            {% for member in members  %}
                <tr>
                  <th>#{{ member.id }}</th>
                  <td>{{ member.name }}</td>
                  <td>{{ member.kl }}</td>
                  <td>{{ member.bonusMalus }}</td>
                  <td>{{ member.kl + member.bonusMalus }}</td>
                  <td>
                      {% if (member.disabled == 1) %}
                      	<span class="text-danger"><b>Bannis</b></span>
                      {% else %}
                      	<span class="text-success"><b>Actif</b></span>
                      {% endif %}
                  </td>
                  <td>
					<a href="{{path('member_edit', {id : member.id})}}" title="editer"><span class="oi oi-pencil"></span></a>
                   
                    {% if (member.disabled == 1) %}
                      	<a href="{{path('member_disabled', {id : member.id})}}" title="Définir en tant qu'actif"><span class="oi oi-circle-check"></span></a>
                    {% else %}
                      	<a href="{{path('member_disabled', {id : member.id})}}" title="Définir en tant que bannis"><span class="oi oi-circle-x"></span></a>
                    {% endif %}
                    
                    <a href="{{path('member_delete', {id : member.id})}}" title="supprimer"><span class="oi oi-x"></span></a>
                  </td>
                </tr>
           {% endfor %}
  		</tbody>
	</table>
{% endblock %}